name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel

    - name: Build Sorbet
      run: ./bazel build //main:sorbet --config=release-linux

    - name: Test Sorbet
      run: ./bazel test test
